create sql

CREATE TABLE carriers (
	id BIGINT IDENTITY(1,1) PRIMARY KEY,
	carrier_code varchar(50) NOT NULL,
	reserved BIT DEFAULT 0 NULL,
	error BIT DEFAULT 0 NULL,
	distance int DEFAULT 0 NULL,
	created_at DATETIME2 DEFAULT GETDATE(),
);

CREATE TABLE equipments (
	id BIGINT IDENTITY(1,1) PRIMARY KEY,
	equipment_code varchar(50) NOT NULL,
	"location" varchar(50) NULL,
	status varchar(20) NULL,
	created_at DATETIME2 DEFAULT GETDATE(),
);

CREATE TABLE ALARM (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ALARM_DEF_ID varchar(50) NOT NULL,
    EQUIPMENT_ID varchar(50) NOT NULL,
    ALARM_STATE varchar(50) NOT NULL,
    CREATE_TIME DATETIME2,
    CLEAR_TIME DATETIME2,
    EVENT_NAME varchar(50),
    TIME_KEY varchar(50),
    EVENT_TIME DATETIME2,
    EVENT_USER varchar(50),
    EVENT_COMMENT varchar(50)
);


CREATE TABLE ALARM_HISTROY (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ALARM_DEF_ID varchar(50) NOT NULL,
    EQUIPMENT_ID varchar(50) NOT NULL,
    ALARM_STATE varchar(50) NOT NULL,
    CREATE_TIME DATETIME2,
    CLEAR_TIME DATETIME2,
    EVENT_NAME varchar(50),
    TIME_KEY varchar(50) ,
    EVENT_TIME DATETIME2,
    EVENT_USER varchar(50),
    EVENT_COMMENT varchar(50)
);


CREATE TABLE ALARM_DEF (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ALARM_CODE_NAME varchar(50) NOT NULL,
    ALARM_TYPE varchar(50) NOT NULL,
    DESCRIPTION varchar(50),
    ALARM_LEVEL varchar(50) NOT NULL,
    DATA_STATE varchar(50) ,
    CHECK_OUT_STATE varchar(50),
    CHECK_OUT_TIME DATETIME2,
    CHECK_OUT_USER varchar(50) ,
    EVENT_NAME varchar(50),
    TIME_KEY varchar(50),
    EVENT_TIME DATETIME2,
    EVENT_USER varchar(50),
    EVENT_COMMENT varchar(50)
);


CREATE TABLE ALARM_DEF_HISTORY (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ALARM_CODE_NAME varchar(50) NOT NULL,
    ALARM_TYPE varchar(50) NOT NULL,
    DESCRIPTION varchar(50),
    ALARM_LEVEL varchar(50) NOT NULL,
    DATA_STATE varchar(50) ,
    CHECK_OUT_STATE varchar(50),
    CHECK_OUT_TIME DATETIME2,
    CHECK_OUT_USER varchar(50) ,
    EVENT_NAME varchar(50),
    TIME_KEY varchar(50),
    EVENT_TIME DATETIME2,
    EVENT_USER varchar(50),
    EVENT_COMMENT varchar(50)
);


CREATE TABLE ALARM_ACTION (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ALARM_ACTION_NAME varchar(50) NOT NULL,
    ACTION_TYPE varchar(50) NOT NULL,
    ALARM_DEF_ID BIGINT NOT NULL,
    DESCRIPTION varchar(50),
    DATA_STATE varchar(50),
    CHECK_OUT_STATE varchar(50),
    CHECK_OUT_TIME DATETIME2,
    CHECK_OUT_USER varchar(50),
    EVENT_NAME varchar(50),
    TIME_KEY varchar(50),
    EVENT_TIME DATETIME2,
    EVENT_USER varchar(50),
    EVENT_COMMENT varchar(50)
);

CREATE TABLE ALARM_ACTION_HISTORY (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ALARM_ACTION_NAME varchar(50) NOT NULL,
    ACTION_TYPE varchar(50) NOT NULL,
    ALARM_DEF_ID BIGINT NOT NULL,
    DESCRIPTION varchar(50),
    DATA_STATE varchar(50),
    CHECK_OUT_STATE varchar(50),
    CHECK_OUT_TIME DATETIME2,
    CHECK_OUT_USER varchar(50),
    EVENT_NAME varchar(50),
    TIME_KEY varchar(50),
    EVENT_TIME DATETIME2,
    EVENT_USER varchar(50),
    EVENT_COMMENT varchar(50)
);

CREATE TABLE ALARM_ACTION_USER_GROUP (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_GROUP_NAME varchar(50) NOT NULL,
    EVENT_NAME varchar(50),
    TIME_KEY varchar(50),
    EVENT_TIME DATETIME2,
    EVENT_USER varchar(50),
    EVENT_COMMENT varchar(50)
);

CREATE TABLE ALARM_ACTION_USER_GROUP_HISTORY (
	ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_GROUP_NAME varchar(50) NOT NULL,
    EVENT_NAME varchar(50),
    TIME_KEY varchar(50),
    EVENT_TIME DATETIME2,
    EVENT_USER varchar(50),
    EVENT_COMMENT varchar(50)
);
