server:
  port: 8081
spring:
  application:
    name: mng
  profiles:
    active: pex # 또는 rabbitmq | scheduler,rabbitmq | dispatcher 등으로 설정 가능
  datasource:
    jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=myprojecttest;encrypt=false;
    username: sa
    password: th!131030
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      pool-name: mssql-pool
      leak-detection-threshold: 2000   # ← ms 단위
  jpa:
    hibernate:
      ddl-auto: none # 개발 초기에는 update 또는 create, 운영에서는 none 또는 validate
    properties:
      hibernate:
#        format_sql: true # SQL 로그를 예쁘게 포맷팅
#        highlight_sql: true # ANSI 컬러 하이라이트 (지원 콘솔일 때)
        generate_statistics: true        # 통계 수집 (org.hibernate.stat 로깅과 함께)
    show-sql: true # 실행되는 SQL 쿼리를 로그로 보여줌
  # DB2 데이터소스 추가
  db2-datasource:
    jdbc-url: jdbc:db2://localhost:50000/testdb # 실제 DB2 URL로 변경해주세요
    username: db2inst1 # 실제 DB2 계정으로 변경해주세요
    password: 1234 # 실제 DB2 비밀번호로 변경해주세요
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    hikari:
      pool-name: db2-pool
      leak-detection-threshold: 2000   # ← ms 단위
logging:
  level:
    # === Hibernate (Spring Boot 3/Hibernate 6 기준) ===
    org.hibernate.SQL: DEBUG                     # 실행되는 SQL
    org.hibernate.orm.jdbc.bind: TRACE           # 바인드 파라미터 값
    org.hibernate.orm.jdbc.extract: DEBUG        # JDBC 결과 추출(선택)
    org.hibernate.type.descriptor.sql: TRACE     # (버전에 따라) 추가 바인딩 상세
    org.hibernate.stat: DEBUG                    # 2차캐시/쿼리카운트 등 통계 로그
    # === JPA (Spring Data) ===
    org.springframework.orm.jpa: DEBUG           # JPA 트랜잭션 등 프레임워크 레벨
    org.springframework.transaction: DEBUG       # 트랜잭션 경계 로그
    # === HikariCP ===
    #com.zaxxer.hikari: DEBUG                     # 풀 라이프사이클/대여/반납 등 상세
    #com.zaxxer.hikari.pool.HikariPool: DEBUG     # 풀 상태 변화 상세
    com.zaxxer.hikari.HikariConfig: DEBUG        # 구성 파라미터 덤프
    net:
      javacrumbs:
        shedlock: DEBUG
---
# 'rabbitmq' 프로필이 활성화될 때만 이 설정이 적용됩니다.
spring:
  config:
    activate:
      on-profile: pex,tex,dispatcher
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10